before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - linux
  - darwin 
archive:
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  name_template: "{{ .ProjectName  }}-{{ .Os  }}-{{ .Arch  }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
